tap "Goles/battery"
tap "caskroom/cask"
tap "neovim/neovim"

# Install docker dependencies
brew "docker"
brew "docker-machine"
cask "virtualbox"

# Use better apps for browsing, listening to music, and communicating
cask "google-chrome"
cask "hyper"
cask "notion"
cask "sketch"
cask "slack"
cask "spotify"
cask "vlc"

# Utilities
cask "alfred"
cask "apptrap"
cask "caffeine"
cask "google-backup-and-sync"
cask "google-hangouts"
cask "google-photos-backup"
cask "imageoptim"
cask "licecap"
cask "marked"
cask "phoenix"
cask "pixelstick"
cask "skitch"

# Install dev environment requirements
brew "battery"
brew "fish"
brew "fzf"
brew "gist"
brew "hub"
brew "jq"
brew "neovim"
brew "python3"
brew "reattach-to-user-namespace"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "wget"
