version: "2.1"

services:
  web:
    build: .
    command: bundle exec ruby server.rb
    # links:
    #   - db
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:4567

  # db:
  #   image: postgres
  #   expose:
  #     - 5432
